In [12]:
import pandas as pd

In [13]:
CB = pd.read_csv('CoffeeBean.csv', encoding='CP949', index_col=0, header=0, engine='python')

In [14]:
CB.head()

     store                              address         phone
0  학동역 DT점                 서울시 강남구 학동로 211 1층    02-3444-9973
1     차병원점            서울시 강남구 논현로 566 강남차병원1층     02-538-7615
2    강남대로점                서울시 서초구 강남대로 369 1층     02-588-5778
3    강남에스점                 서울시 서초구 서초 1306-3호     02-593-5095
4    청담에스점  서울시 강남구 압구정로 461 네이처포엠빌딩B108,109호     02-548-6052

In [15]:
addr = []

for address in CB.address:
    addr.append(str(address).split())

#작업 내용 확인용 출력
print('데이터 개수 : %d' % len(addr))
addr

데이터 개수 : 246

[['서울시', '강남구', '학동로', '211', '1층'],
 ['서울시', '강남구', '논현로', '566', '강남차병원1층'],
 ['서울시', '서초구', '강남대로', '369', '1층'],
 ['서울시', '서초구', '서초', '1306-3호'],
 ['서울시', '강남구', '압구정로', '461', '네이처포엠빌딩B108,109호'],
 ['서울시', '강남구', '도산대로', '126'],
 ['서울시', '강남구', '논현로', '842', '압구정빌딩1층'],
 ['서울시', '강남구', '논현로', '512', '지상1,2층'],
 ['서울시', '서초구', '강남대로', '213', '24호', '지하1층'],
 ['서울시', '강남구', '삼성로', '716', 'LEE76빌딩2층'],
 ['서울', '서초구', '반포동', '736-17', 'P빌딩', '2층'],
 ['서울시', '강남구', '언주로', '30길', '10,112', '현대비젼21', '112호'],
 ['서울시', '강남구', '선릉로', '749', '1,2층'],
 ['서울시', '강남구', '도산대로49길', '13', '1층', '17,18호'],
 ['서울시', '강남구', '선릉로', '157길', '12', '석전빌딩', '1~4층'],
 ['서울시', '서초구', '강남대로', '51길', '1', '511', 'TOWER', '1층'],
 ['서울시', '강남구', '논현', '231-13호', '팍스타워지하1층'],
 ['서울', '강남구', '영동대로', '513', '컨벤션별관A동', '지하', '2층'],
 ['서울시', '강남구', '영동대로', '511', '트레이드타워', '지하1층'],
 ['서울시', '강남구', '영동대로', '607', '1,2층'],
 ['서울시', '서초구', '신반포로', '23', '1141호', '엘루체백화점내1층1013~1015호'],
 ['서울시', '송파구', '석촌호수로', '118', '1층'],
 ['서울시', '서초구', '서초동', '1685-8호', '101~2호,113~4호,121호'],
 ['서울시', '강남구', '논현로', '717', '1층'],
 ['서울시', '서초구', '서초대로74길', '11', '지하2층'],
 ['서울시', '서초구', '서초대로74길', '4', '삼성생명보험서초타워내지하1층'],
 ['서울특별시', '서초구', '방배중앙로', '187'],
 ['서울시', '강남구', '테헤란로', '20길', '10', '쓰리엠타워1층'],
 ['서울시', '강남구', '테헤란로', '70길', '12', '1층'],
 ['서울시', '강남구', '봉은사로', '628', '엘슨빌딩1층'],
 ['서울시', '송파구', '오금로', '11길', '7'],
 ['서울시', '강남구', '논현로', '38길', '42', '418호'],
 ['서울시', '서초구', '서초중앙로', '43', '로얄타워1층'],
 ['서울시', '강남구', '테헤란로4길', '28', '826-28호', '1층'],
 ['서울시', '강남구', '테헤란로87길', '36', '공항타워', '1층'],
 ['서울시', '강남구', '도산대로', '67길', '7,파크빌딩', '1층'],
 ['서울', '종로구', '서린동', '136', '센트리얼빌딩', '1층'],
 ['서울시', '종로구', '새문안로3길', '23', '경희궁아침상가4단지105외'],
 ['서울시', '마포구', '홍익로', '6길', '26'],
 ['서울시', '중구', '순화202', '1-94', '프레이저플레이스레지던스1층'],
 ['서울시', '종로구', '청계천로', '83', '11-4호', '지하1,지상1~3층'],
 ['서울', '중구', '남대문로7길', '16', '한컴빌딩', '1층'],
 ['서울시', '광진구', '광나루로56길', '85', '테크노마트9층35호'],
 ['서울시', '동대문구', '이문로', '106', '1~3층'],
 ['서울시', '성북구', '개운사길8', '101-3', '1층'],
 ['서울시', '중구', '칠패로', '27', '151호'],
 ['서울', '종로구', '새문안로', '9길', '25', '1층'],
 ['서울시', '서대문구', '창천', '18-26호', 'B1'],
 ['서울시', '광진구', '자양동', '227-342호', '롯데백화점', '옆', '더클래식500건물', '1층'],
 ['서울시', '종로구', '사직로', '130,1', '현대적선빌딩1층'],
 ['서울시', '노원구', '한글비석로', '263', '1층'],
 ['서울시', '중구', '한강대로', '416', '지하1층'],
 ['서울시', '양천구', '목동동로', '293', '현대41타워1층'],
 ['서울', '영등포구', '국제금융로', '52', '심팩빌딩', '1층'],
 ['서울시', '영등포구', '의사당대로', '97', '26-4', '교보증권빌딩1층'],
 ['서울시', '금천구', '시흥대로', '201', '1층'],
 ['서울시', '영등포구', '여의서로', '43', '한서리버파크2층'],
 ['부산광역시', '중구', '창선동', '2가', '8-2'],
 ['인천광역시', '남동구', '예술로', '138', '지상1,2층'],
 ['대전시', '서구', '문정로76', '1층'],
 ['경기도', '고양시', '일산동구', '정발산로', '24', 'I동103~203호'],
 ['경기도', '성남시', '분당구', '분당로53번길', '11', '1층2,3호'],
 ['경기도', '성남시', '분당구', '황새울로', '326', '서현빌딩상가내2층'],
 ['경기도', '성남시', '분당구', '야탑로65번길', '16,', '분당차병원', '신관동', '1층', '101호(야탑동)'],
 ['경기도', '성남시', '분당구', '황새울로', '214번길8', 'MSPlaza내1층'],
 ['경기도', '화성시', '노작로', '199', '동탄라마다호텔107호~111호'],
 ['경남', '창원시', '성산구', '중앙대로', '104', '마이우스오피스텔', '123호', '207호'],
 ['충북', '청주시', '흥덕구', '대농로', '17', '지웰시티몰', '1층', '124-1,125,126호'],
 ['서울', '중구', '세종대로', '136', '파이낸스빌딩', '지하2층'],
 ['서울시', '강남구', '테헤란로', '8길', '42', '1층'],
 ['서울시', '중구', '태평로1', '84호', 'SFC빌딩B1,1-4'],
 ['서울시', '중구', '후암로110', '581호', '서울시티타워1층'],
 ['서울시', '송파구', '양재대로', '1222', '올림픽선수A', '1층212~3호'],
 ['서울시', '종로구', '대학로', '12길', '62', '지하1층,지상1,2층'],
 ['서울시', '종로구', '낙원동', '272', '오라카이스위츠', '1층'],
 ['서울시', '강남구', '테헤란로', '312', '707-2번지1층'],
 ['서울시', '관악구', '관악로', '161', '층일부', '2,3층'],
 ['서울시', '강남구', '봉은사로', '524', '코엑스', '인터컨티넨탈아케이드'],
 ['서울시', '강남구', '논현로', '167길', '9', '낙산프라자', '1층'],
 ['서울시', '구로구', '경인로', '662', '디큐브시티', '4층'],
 ['서울시', '영등포구', '국제금융로', '20', '1층'],
 ['서울시', '강남구', '선릉로93길', '6(역삼동)', '1층'],
 ['서울시', '강남구', '테헤란로1길', '29', '1층일부', '및', '2.3층'],
 ['서울시', '강남구', '삼성로', '551', '1층,2층'],
 ['서울시', '강남구', '선릉로86길', '11'],
 ['서울시', '종로구', '율곡로', '47', '1,2층'],
 ['서울시', '서초구', '강남대로', '449-3', '알고코리아빌딩', '1,2층'],
 ['서울시', '영등포구', '국제금융로10', 'IFC', 'Mall', 'L2'],
 ['서울시', '마포구', '상암산로', '82', 'SBS프리즘타워', '1층'],
 ['서울시', '금천구', '디지털로9길', '23', '마리오-2관', '패션타워3층'],
 ['경기도', '화성시', '장덕동', '현대연구소로150', '현대자동차남양연구소', '설계1동1F'],
 ['서울시', '강남구', '가로수길', '83'],
 ['서울시', '서초구', '강남대로', '267', '2,3층'],
 ['서울시', '강동구', '천호대로', '1096', '1,2F'],
 ['경기도', '수원시', '팔달구', '권광로', '195', '학산빌딩1층'],
 ['경기도', '성남시', '분당구', '동판교로177번길', '25'],
 ['경기도', '고양시', '일산서구', '한류월드로', '300', '원마운트스포츠몰', '1층'],
 ['경기', '화성시', '장덕동', '현대연구소로150', '현대자동차남양연구소', 'C1구역식당1F'],
 ['서울시', '영등포구', '의사당대로', '97', '교보증권빌딩', '2층'],
 ['서울시', '강남구', '압구정로29길65', '지하1층'],
 ['서울시', '강남구', '테헤란로143', '고운빌딩1층'],
 ['인천광역시', '부평구', '시장로29', '1,2층'],
 ['서울시', '강남구', '강남대로442', '흥국화재빌딩', '2층'],
 ['서울시', '구로구', '디지털로300', '지밸리비즈플라자', '2층'],
 ['서울시', '서초구', '방배로178', '유중아트센터1층'],
 ['서울시', '강남구', '테헤란로87길22', '도심공항터미널', '지하1층'],
 ['서울시', '영등포구', '영중로15', '타임스퀘어', '1층'],
 ['서울시', '강남구', '봉은사로207', 'KJ타워1층'],
 ['서울시', '강남구', '테헤란로521', '파르나스몰', '지하1층'],
 ['서울시', '종로구', '새문안로5가길', '7', '1층', '일부'],
 ['경기도', '화성시', '장덕동', '현대연구소로150', '현대자동차남양연구소', 'PT동', '1층'],
 ['경기', '김포시', '고촌읍', '전호리', '654번지', '현대프리미엄아울렛김포3층', '618호'],
 ['서울시', '영등포구', '국제금융로8길6', '신영증권별관빌딩2층'],
 ['서울시', '용산구', '이태원로220(한남동)', '1층'],
 ['서울시', '서초구', '서초대로73길12', '세계빌딩1층'],
 ['경기도', '수원시', '영통구', '이의동', '1332', '광교아브뉴프랑', '1층', 'A122,123호'],
 ['서울시', '광진구', '아차산로563(광장동)', '대한제지빌딩', '로비층'],
 ['서울시', '송파구', '올림픽로100', '효창타워1층'],
 ['서울시', '관악구', '남부순환로1909', '1,2층'],
 ['인천광역시', '중구', '공항로272', '인천국제공항탑승동3층', 'FB-C5-57'],
 ['인천광역시', '중구', '공항로272', '인천국제공항탑승동3층', 'FB-C5-68'],
 ['서울시', '송파구', '석촌호수로', '222', '제이타워', '1층'],
 ['서울시', '양천구', '오목로', '350', '목동썬텍씨티빌딩', '1층,2층'],
 ['서울시', '중구', '남대문로10길', '6', '1,2층'],
 ['경기', '이천시', '부발읍', '하이닉스반도체'],
 ['인천광역시', '연수구', '송도국제대로', '165(송도동)', '홈플러스송도점1층'],
 ['서울시', '강동구', '강동대로193', '1층'],
 ['서울시', '성북구', '인촌로24길', '25', '(안암동5가)', '2층,3층'],
 ['서울시', '강남구', '영동대로85길', '9', '(대치동)', '서전빌딩1층'],
 ['경기도', '안양시', '동안구', '평촌대로', '223번길', '41(호계동', '1045-9)', '2층'],
 ['서울특별시', '강남구', '삼성로86길', '11', '거봉빌딩', '1층'],
 ['서울시', '마포구', '성암로301', 'KLID한국지역정보개발원', '1층'],
 ['경기도', '성남시', '분당구', '정자일로', '227(정자동)', '백궁지엔느주차전용빌딩', '1층'],
 ['서울특별시', '강남구', '봉은사로108', '글라스톤빌딩1층'],
 ['서울시', '강서구', '화곡6동', '1095번지', '1층'],
 ['서울시', '서대문구', '대신동', '50-5', '1층,2층(B동)'],
 ['서울시', '동대문구', '장안동', '372-1,', '1층', '일부', '및', '2층', '전체'],
 ['경기도', '수원시', '영통구', '영통로', '214번길', '8', '1층'],
 ['서울시', '서초구', '동산로', '1', '1층'],
 ['서울시', '영등포구', '문래동6가', '5번지', '1층'],
 ['부산시', '해운대구', '해운대', '해변로277', '다옴빌딩1층'],
 ['서울시', '강남구', '역삼동', '718-20', '태광타워', '1층'],
 ['경기', '용인시', '수지구', '손곡로', '95', '송란빌딩', '1층'],
 ['경기도', '파주시', '청암로', '17번길', '17', '1층'],
 ['서울시', '서초구', '신반포로47길', '5', '건물전체', '1~3층'],
 ['서울시', '강동구', '올림픽로', '659', '쌍용플래티넘리버', '1층'],
 ['서울시', '마포구', '양화로18안길', '7', '2층'],
 ['경기도', '군포시', '광정로58', '1층', '104호', '및', '2층'],
 ['강원도', '원주시', '봉화로1', 'AK플라자원주점', '1층'],
 ['경기도', '고양시', '덕양구', '화신로260번길', '26', '동민프라자', '1층', '103~107호'],
 ['서울특별시', '강남구', '테헤란로', '111', '2층'],
 ['서울특별시', '서초구', '서초대로', '397', '부띠크모나코', '1층'],
 ['서울특별시', '송파구', '송파대로', '111', '송파파크하비오', '205동', '1층', '110-113'],
 ['서울특별시', '송파구', '법원로', '114,', '엠스테이트', 'B동', '지하', '1층,', 'B145-147'],
 ['서울특별시', '중랑구', '망우로', '291', '1층'],
 ['서울특별시', '강동구', '동남로', '885', '양지빌딩', '1층'],
 ['서울시', '노원구', '노해로', '490,', '길빌딩', '2층'],
 ['서울시', '종로구', '종로', '70', '2층'],
 ['경기도', '평택시', '평남로', '862,', '로이드빌딩', '1층'],
 ['서울시', '송파구', '방이동', '44-2,', '장은빌딩', '1층'],
 ['서울특별시', '강남구', '도곡동', '543-1,', '지오빌딩', 'B1층'],
 ['서울특별시',
  '강북구',
  '한천로',
  '139길',
  '25,',
  '1층',
  '일부',
  '및',
  '2층',
  '(수유동',
  '191-70)'],
 ['인천', '연수구', '송도과학로', '16번길', '33-4', 'D동', '119호,207호'],
 ['서울특별시', '광진구', '구의강변로', '106', '삼성쉐르빌', '1층'],
 ['서울특별시', '영등포구', '국제금융로8길31', '여의도SK증권빌딩점', '1층'],
 ['서울특별시', '송파구', '충민로', '66', '가든파이브', '라이프동', '테크노관', '1층'],
 ['서울시', '송파구', '위례광장로', '230', '위례2차', '아이파크', 'B동', '1층'],
 ['서울특별시', '성북구', '삼선교로', '12', '1층'],
 ['서울특별시', '강남구', '도곡로', '408', '디마크빌딩', '1층'],
 ['서울특별시', '강남구', '강남대로112길', '20', '1층,', '2층'],
 ['경기도', '수원시', '장안구', '경수대로', '989'],
 ['서울특별시', '마포구', '양화로', '196(동교동)'],
 ['경기도', '성남시', '수정구', '수정로', '190', '(신흥동)'],
 ['서울시', '은평구', '은평로', '121(응암동),', '메디컬빌딩'],
 ['경기도', '수원시', '권선구', '수인로', '291(구운동),', '이마트', '서수원점', '1층'],
 ['서울특별시', '강서구', '강서로', '457(마곡동)'],
 ['경기', '수원시', '장안구', '서부로', '2066,', '성균관대', '자연과학', '캠퍼스', 'N센터', '1층'],
 ['서울특별시', '강서구', '마곡동로', '55', '마커스빌딩', '1층'],
 ['서울', '송파구', '방이동', '206-11'],
 ['서울시', '영등포구', '국제금융로10', 'IFC', 'Mall', 'L2(2층)'],
 ['경기도', '화성시', '능동', '453-4,453-8,454-1', '소재', '건물(1~3층)'],
 ['경기도', '수원시', '팔달구', '인계로79', '(인계동)'],
 ['인천광역시', '중구', '운서동', '2868', '인천공항', '제2터미널', '1층', '연번(23-124)'],
 ['부산광역시', '부산진구', '서전로', '12,', '1층'],
 ['경기도', '성남시', '분당구', '야탑로64', 'DS타워', '1층'],
 ['서울시', '용산구', '한강대로95'],
 ['서울특별시', '강남구', '선릉로', '433', '세방빌딩', '1층'],
 ['경기도', '광명시', '양지로16', '아브뉴프랑', '지하', '2층', '(주)커피빈코리아', '광명아브뉴프랑점'],
 ['서울특별시', '종로구', '새문안로', '91', '고려빌딩', '1,2층'],
 ['서울특별시', '송파구', '법원로6길', '11', '환인빌딩', '1층'],
 ['서울시', '동대문구', '경희대로', '10', '(회기동)'],
 ['경기도', '파주시', '문발로', '131'],
 ['경상남도', '창원시', '성산구', '원이대로', '320,', '더시티세븐S-105호(대원동)'],
 ['서울특별시', '종로구', '종로3길', '34'],
 ['서울시', '마포구', '와우산로10길', '3,', '엘케이빌딩', '1~3층'],
 ['경기도', '안양시', '동안구', '시민대로', '260,', '1층', '104,105호'],
 ['경기도', '하남시', '미사대로', '750,', '신세계백화점', '지하1층', '식품관'],
 ['서울시', '종로구', '우정국로', '26', '센트로폴리스', '1층', 'Retail', '1-5,6'],
 ['서울특별시', '송파구', '올림픽로35길', '123', '1층'],
 ['부산', '부산진구', '서면로', '62-1', '에이스메디컬타워', '1F'],
 ['인천시', '중구', '신도시남로', '142번길', '6', '(메가스타', '영종', '139,140,141호)'],
 ['서울시', '중구', '장충동2가', '188-11,', '188-4,', '188-5'],
 ['부산', '해운대구', '센텀3로', '20', '해운대센텀호텔', '1F', '101호'],
 ['서울', '서초구', '서초중앙로', '156,', '1층'],
 ['경기도', '부천시', '부천로25'],
 ['부산', '중구', '해관로', '1', '희남빌딩', '1층'],
 ['광주', '서구', '상무중앙로', '9,', '동양빌딩', '1F'],
 ['경기도', '김포시', '태장로', '819'],
 ['서울특별시', '서초구', '반포대로70'],
 ['경기도', '남양주시', '경춘로', '1641'],
 ['서울시', '강남구', '봉은사로', '331', 'SH빌딩점', 'B1-1층'],
 ['서울시', '강서구', '강서로', '162'],
 ['경기도', '부천시', '옥길동', '768', '부천스타필드시티점', '4층'],
 ['인천시', '연수구', '컨벤시아대로', '60,', '1층'],
 ['광주광역시', '동구', '서남동', '서석로', '44', '1층', '~', '2층'],
 ['대구광역시', '중구', '동성로3길', '106'],
 ['서울', '강남구', '대치동', '943-2', '루첸타워', '1층', '로비'],
 ['경기도', '수원시', '팔달구', '덕영대로', '924', 'AK플라자', '4층'],
 ['서울시', '중구', '을지로', '35', '하나은행', '을지로본점', '24F', '내', '스마트워크센터'],
 ['서울시', '강남구', '테헤란로69길', '5', 'DT센터점', '1층'],
 ['서울시', '서초구', '강남대로', '563', '페이토플라자', '1층', '(', '잠원동', '37-1', ')'],
 ['서울시', '용산구', '장문로', '23', '몬드리안', '서울', '이태원호텔', '101호'],
 ['광주광역시', '남구', '봉선로', '168'],
 ['서울시', '노원구', '동일로', '1405,', '1층', '일부'],
 ['서울', '강남구', '광평로', '51길', '6-23', '원방테크사옥', '1층'],
 ['서울시', '송파구', '송파대로', '345', '(', '헬리오시티상가', '3블럭', 'A동', 'B1층', '22호', ')'],
 ['서울', '중구', '남대문로10길', '33', '1F'],
 ['서울시', '서초구', '서초중앙로', '209,', '해성빌딩', '1층'],
 ['경기도', '고양시', '일산동구', '정발산로', '38'],
 ['부산광역시', '북구', '학사로', '8', '(화명동', '2312),', '크리스탈타워', '2층', '201~202호'],
 ['경기도', '용인시', '처인구', '역북동', '598-7'],
 ['부산광역시', '중구', '중앙대로', '102', '팬오션빌딩', '1F'],
 ['충남', '천안시', '동남구', '만남로', '48'],
 ['제주도', '제주시', '연북로', '511'],
 ['서울시', '종로구', '대명길', '5'],
 ['경기도', '용인시', '처인구', '포곡읍', '가실리', '156-1', '(파크내', '홀랜드빌리지', '옆', '암스테르담)'],
 ['서울시', '중구', '명동', '10길', '52', '명동역', '신한은행', '사옥', '1층'],
 ['경기도', '안양시', '동안구', '엘에스로', '127', '1층'],
 ['서울', '마포구', '상암산로', '82', 'SBS', '프리즘', '타워', '1층', '로비'],
 ['서울시', '용산구', '한강대로', '23길', '55,', '아이파크몰', '테이스트파크', '7층'],
 ['경기도', '이천시', '대산로288번길', '89,', '행복1마을', '복지A동', '지하1층'],
 ['경남', '진주시', '충의로', '19', 'LH진주사옥', '공감동', '1층'],
 ['서울시', '중구', '을지로', '66', '하나은행', '명동사옥', '1층'],
 ['제주도', '제주시', '애월읍', '애월해안로', '560'],
 ['서울시', '종로구', '성균관로', '25-2', '성균관대학교', '법학관', 'B2'],
 ['경기도', '화성시', '동탄중앙로220', '타임테라스A', '블록', '1층', '110호-1호']]

In [16]:
addr2 = []

# addr에서 행정구역 표준 이름이 아닌 것 수정하기
for i in range(len(addr)):
    if addr[i][0] == "서울": addr[i][0] = "서울특별시"
    elif addr[i][0] == "서울시": addr[i][0] = "서울특별시"
    elif addr[i][0] == "부산시": addr[i][0] = "부산광역시"
    elif addr[i][0] == "인천": addr[i][0] = "인천광역시"
    elif addr[i][0] == "광주": addr[i][0] = "광주광역시"
    elif addr[i][0] == "대전시": addr[i][0] = "대전광역시"
    elif addr[i][0] == "울산시": addr[i][0] = "울산광역시"
    elif addr[i][0] == "세종시": addr[i][0] = "세종특별자치시"
    elif addr[i][0] == "경기": addr[i][0] = "경기도"
    elif addr[i][0] == "충북": addr[i][0] = "충청북도"
    elif addr[i][0] == "충남": addr[i][0] = "충청남도"
    elif addr[i][0] == "전북": addr[i][0] = "전라북도"
    elif addr[i][0] == "전남": addr[i][0] = "전라남도"
    elif addr[i][0] == "경북": addr[i][0] = "경상북도"
    elif addr[i][0] == "경남": addr[i][0] = "경상남도"
    elif addr[i][0] == "제주": addr[i][0] = "제주특별자치도"
    elif addr[i][0] == "제주도": addr[i][0] = "제주특별자치도"
    elif addr[i][0] == "제주시": addr[i][0] = "제주특별자치도"

    addr2.append(' '.join(addr[i]))
addr2 #작업 내용 확인용 출력

['서울특별시 강남구 학동로 211 1층',
 '서울특별시 강남구 논현로 566 강남차병원1층',
 '서울특별시 서초구 강남대로 369 1층',
 '서울특별시 서초구 서초 1306-3호',
 '서울특별시 강남구 압구정로 461 네이처포엠빌딩B108,109호',
 '서울특별시 강남구 도산대로 126',
 '서울특별시 강남구 논현로 842 압구정빌딩1층',
 '서울특별시 강남구 논현로 512 지상1,2층',
 '서울특별시 서초구 강남대로 213 24호 지하1층',
 '서울특별시 강남구 삼성로 716 LEE76빌딩2층',
 '서울특별시 서초구 반포동 736-17 P빌딩 2층',
 '서울특별시 강남구 언주로 30길 10,112 현대비젼21 112호',
 '서울특별시 강남구 선릉로 749 1,2층',
 '서울특별시 강남구 도산대로49길 13 1층 17,18호',
 '서울특별시 강남구 선릉로 157길 12 석전빌딩 1~4층',
 '서울특별시 서초구 강남대로 51길 1 511 TOWER 1층',
 '서울특별시 강남구 논현 231-13호 팍스타워지하1층',
 '서울특별시 강남구 영동대로 513 컨벤션별관A동 지하 2층',
 '서울특별시 강남구 영동대로 511 트레이드타워 지하1층',
 '서울특별시 강남구 영동대로 607 1,2층',
 '서울특별시 서초구 신반포로 23 1141호 엘루체백화점내1층1013~1015호',
 '서울특별시 송파구 석촌호수로 118 1층',
 '서울특별시 서초구 서초동 1685-8호 101~2호,113~4호,121호',
 '서울특별시 강남구 논현로 717 1층',
 '서울특별시 서초구 서초대로74길 11 지하2층',
 '서울특별시 서초구 서초대로74길 4 삼성생명보험서초타워내지하1층',
 '서울특별시 서초구 방배중앙로 187',
 '서울특별시 강남구 테헤란로 20길 10 쓰리엠타워1층',
 '서울특별시 강남구 테헤란로 70길 12 1층',
 '서울특별시 강남구 봉은사로 628 엘슨빌딩1층',
 '서울특별시 송파구 오금로 11길 7',
 '서울특별시 강남구 논현로 38길 42 418호',
 '서울특별시 서초구 서초중앙로 43 로얄타워1층',
 '서울특별시 강남구 테헤란로4길 28 826-28호 1층',
 '서울특별시 강남구 테헤란로87길 36 공항타워 1층',
 '서울특별시 강남구 도산대로 67길 7,파크빌딩 1층',
 '서울특별시 종로구 서린동 136 센트리얼빌딩 1층',
 '서울특별시 종로구 새문안로3길 23 경희궁아침상가4단지105외',
 '서울특별시 마포구 홍익로 6길 26',
 '서울특별시 중구 순화202 1-94 프레이저플레이스레지던스1층',
 '서울특별시 종로구 청계천로 83 11-4호 지하1,지상1~3층',
 '서울특별시 중구 남대문로7길 16 한컴빌딩 1층',
 '서울특별시 광진구 광나루로56길 85 테크노마트9층35호',
 '서울특별시 동대문구 이문로 106 1~3층',
 '서울특별시 성북구 개운사길8 101-3 1층',
 '서울특별시 중구 칠패로 27 151호',
 '서울특별시 종로구 새문안로 9길 25 1층',
 '서울특별시 서대문구 창천 18-26호 B1',
 '서울특별시 광진구 자양동 227-342호 롯데백화점 옆 더클래식500건물 1층',
 '서울특별시 종로구 사직로 130,1 현대적선빌딩1층',
 '서울특별시 노원구 한글비석로 263 1층',
 '서울특별시 중구 한강대로 416 지하1층',
 '서울특별시 양천구 목동동로 293 현대41타워1층',
 '서울특별시 영등포구 국제금융로 52 심팩빌딩 1층',
 '서울특별시 영등포구 의사당대로 97 26-4 교보증권빌딩1층',
 '서울특별시 금천구 시흥대로 201 1층',
 '서울특별시 영등포구 여의서로 43 한서리버파크2층',
 '부산광역시 중구 창선동 2가 8-2',
 '인천광역시 남동구 예술로 138 지상1,2층',
 '대전광역시 서구 문정로76 1층',
 '경기도 고양시 일산동구 정발산로 24 I동103~203호',
 '경기도 성남시 분당구 분당로53번길 11 1층2,3호',
 '경기도 성남시 분당구 황새울로 326 서현빌딩상가내2층',
 '경기도 성남시 분당구 야탑로65번길 16, 분당차병원 신관동 1층 101호(야탑동)',
 '경기도 성남시 분당구 황새울로 214번길8 MSPlaza내1층',
 '경기도 화성시 노작로 199 동탄라마다호텔107호~111호',
 '경상남도 창원시 성산구 중앙대로 104 마이우스오피스텔 123호 207호',
 '충청북도 청주시 흥덕구 대농로 17 지웰시티몰 1층 124-1,125,126호',
 '서울특별시 중구 세종대로 136 파이낸스빌딩 지하2층',
 '서울특별시 강남구 테헤란로 8길 42 1층',
 '서울특별시 중구 태평로1 84호 SFC빌딩B1,1-4',
 '서울특별시 중구 후암로110 581호 서울시티타워1층',
 '서울특별시 송파구 양재대로 1222 올림픽선수A 1층212~3호',
 '서울특별시 종로구 대학로 12길 62 지하1층,지상1,2층',
 '서울특별시 종로구 낙원동 272 오라카이스위츠 1층',
 '서울특별시 강남구 테헤란로 312 707-2번지1층',
 '서울특별시 관악구 관악로 161 층일부 2,3층',
 '서울특별시 강남구 봉은사로 524 코엑스 인터컨티넨탈아케이드',
 '서울특별시 강남구 논현로 167길 9 낙산프라자 1층',
 '서울특별시 구로구 경인로 662 디큐브시티 4층',
 '서울특별시 영등포구 국제금융로 20 1층',
 '서울특별시 강남구 선릉로93길 6(역삼동) 1층',
 '서울특별시 강남구 테헤란로1길 29 1층일부 및 2.3층',
 '서울특별시 강남구 삼성로 551 1층,2층',
 '서울특별시 강남구 선릉로86길 11',
 '서울특별시 종로구 율곡로 47 1,2층',
 '서울특별시 서초구 강남대로 449-3 알고코리아빌딩 1,2층',
 '서울특별시 영등포구 국제금융로10 IFC Mall L2',
 '서울특별시 마포구 상암산로 82 SBS프리즘타워 1층',
 '서울특별시 금천구 디지털로9길 23 마리오-2관 패션타워3층',
 '경기도 화성시 장덕동 현대연구소로150 현대자동차남양연구소 설계1동1F',
 '서울특별시 강남구 가로수길 83',
 '서울특별시 서초구 강남대로 267 2,3층',
 '서울특별시 강동구 천호대로 1096 1,2F',
 '경기도 수원시 팔달구 권광로 195 학산빌딩1층',
 '경기도 성남시 분당구 동판교로177번길 25',
 '경기도 고양시 일산서구 한류월드로 300 원마운트스포츠몰 1층',
 '경기도 화성시 장덕동 현대연구소로150 현대자동차남양연구소 C1구역식당1F',
 '서울특별시 영등포구 의사당대로 97 교보증권빌딩 2층',
 '서울특별시 강남구 압구정로29길65 지하1층',
 '서울특별시 강남구 테헤란로143 고운빌딩1층',
 '인천광역시 부평구 시장로29 1,2층',
 '서울특별시 강남구 강남대로442 흥국화재빌딩 2층',
 '서울특별시 구로구 디지털로300 지밸리비즈플라자 2층',
 '서울특별시 서초구 방배로178 유중아트센터1층',
 '서울특별시 강남구 테헤란로87길22 도심공항터미널 지하1층',
 '서울특별시 영등포구 영중로15 타임스퀘어 1층',
 '서울특별시 강남구 봉은사로207 KJ타워1층',
 '서울특별시 강남구 테헤란로521 파르나스몰 지하1층',
 '서울특별시 종로구 새문안로5가길 7 1층 일부',
 '경기도 화성시 장덕동 현대연구소로150 현대자동차남양연구소 PT동 1층',
 '경기도 김포시 고촌읍 전호리 654번지 현대프리미엄아울렛김포3층 618호',
 '서울특별시 영등포구 국제금융로8길6 신영증권별관빌딩2층',
 '서울특별시 용산구 이태원로220(한남동) 1층',
 '서울특별시 서초구 서초대로73길12 세계빌딩1층',
 '경기도 수원시 영통구 이의동 1332 광교아브뉴프랑 1층 A122,123호',
 '서울특별시 광진구 아차산로563(광장동) 대한제지빌딩 로비층',
 '서울특별시 송파구 올림픽로100 효창타워1층',
 '서울특별시 관악구 남부순환로1909 1,2층',
 '인천광역시 중구 공항로272 인천국제공항탑승동3층 FB-C5-57',
 '인천광역시 중구 공항로272 인천국제공항탑승동3층 FB-C5-68',
 '서울특별시 송파구 석촌호수로 222 제이타워 1층',
 '서울특별시 양천구 오목로 350 목동썬텍씨티빌딩 1층,2층',
 '서울특별시 중구 남대문로10길 6 1,2층',
 '경기도 이천시 부발읍 하이닉스반도체',
 '인천광역시 연수구 송도국제대로 165(송도동) 홈플러스송도점1층',
 '서울특별시 강동구 강동대로193 1층',
 '서울특별시 성북구 인촌로24길 25 (안암동5가) 2층,3층',
 '서울특별시 강남구 영동대로85길 9 (대치동) 서전빌딩1층',
 '경기도 안양시 동안구 평촌대로 223번길 41(호계동 1045-9) 2층',
 '서울특별시 강남구 삼성로86길 11 거봉빌딩 1층',
 '서울특별시 마포구 성암로301 KLID한국지역정보개발원 1층',
 '경기도 성남시 분당구 정자일로 227(정자동) 백궁지엔느주차전용빌딩 1층',
 '서울특별시 강남구 봉은사로108 글라스톤빌딩1층',
 '서울특별시 강서구 화곡6동 1095번지 1층',
 '서울특별시 서대문구 대신동 50-5 1층,2층(B동)',
 '서울특별시 동대문구 장안동 372-1, 1층 일부 및 2층 전체',
 '경기도 수원시 영통구 영통로 214번길 8 1층',
 '서울특별시 서초구 동산로 1 1층',
 '서울특별시 영등포구 문래동6가 5번지 1층',
 '부산광역시 해운대구 해운대 해변로277 다옴빌딩1층',
 '서울특별시 강남구 역삼동 718-20 태광타워 1층',
 '경기도 용인시 수지구 손곡로 95 송란빌딩 1층',
 '경기도 파주시 청암로 17번길 17 1층',
 '서울특별시 서초구 신반포로47길 5 건물전체 1~3층',
 '서울특별시 강동구 올림픽로 659 쌍용플래티넘리버 1층',
 '서울특별시 마포구 양화로18안길 7 2층',
 '경기도 군포시 광정로58 1층 104호 및 2층',
 '강원도 원주시 봉화로1 AK플라자원주점 1층',
 '경기도 고양시 덕양구 화신로260번길 26 동민프라자 1층 103~107호',
 '서울특별시 강남구 테헤란로 111 2층',
 '서울특별시 서초구 서초대로 397 부띠크모나코 1층',
 '서울특별시 송파구 송파대로 111 송파파크하비오 205동 1층 110-113',
 '서울특별시 송파구 법원로 114, 엠스테이트 B동 지하 1층, B145-147',
 '서울특별시 중랑구 망우로 291 1층',
 '서울특별시 강동구 동남로 885 양지빌딩 1층',
 '서울특별시 노원구 노해로 490, 길빌딩 2층',
 '서울특별시 종로구 종로 70 2층',
 '경기도 평택시 평남로 862, 로이드빌딩 1층',
 '서울특별시 송파구 방이동 44-2, 장은빌딩 1층',
 '서울특별시 강남구 도곡동 543-1, 지오빌딩 B1층',
 '서울특별시 강북구 한천로 139길 25, 1층 일부 및 2층 (수유동 191-70)',
 '인천광역시 연수구 송도과학로 16번길 33-4 D동 119호,207호',
 '서울특별시 광진구 구의강변로 106 삼성쉐르빌 1층',
 '서울특별시 영등포구 국제금융로8길31 여의도SK증권빌딩점 1층',
 '서울특별시 송파구 충민로 66 가든파이브 라이프동 테크노관 1층',
 '서울특별시 송파구 위례광장로 230 위례2차 아이파크 B동 1층',
 '서울특별시 성북구 삼선교로 12 1층',
 '서울특별시 강남구 도곡로 408 디마크빌딩 1층',
 '서울특별시 강남구 강남대로112길 20 1층, 2층',
 '경기도 수원시 장안구 경수대로 989',
 '서울특별시 마포구 양화로 196(동교동)',
 '경기도 성남시 수정구 수정로 190 (신흥동)',
 '서울특별시 은평구 은평로 121(응암동), 메디컬빌딩',
 '경기도 수원시 권선구 수인로 291(구운동), 이마트 서수원점 1층',
 '서울특별시 강서구 강서로 457(마곡동)',
 '경기도 수원시 장안구 서부로 2066, 성균관대 자연과학 캠퍼스 N센터 1층',
 '서울특별시 강서구 마곡동로 55 마커스빌딩 1층',
 '서울특별시 송파구 방이동 206-11',
 '서울특별시 영등포구 국제금융로10 IFC Mall L2(2층)',
 '경기도 화성시 능동 453-4,453-8,454-1 소재 건물(1~3층)',
 '경기도 수원시 팔달구 인계로79 (인계동)',
 '인천광역시 중구 운서동 2868 인천공항 제2터미널 1층 연번(23-124)',
 '부산광역시 부산진구 서전로 12, 1층',
 '경기도 성남시 분당구 야탑로64 DS타워 1층',
 '서울특별시 용산구 한강대로95',
 '서울특별시 강남구 선릉로 433 세방빌딩 1층',
 '경기도 광명시 양지로16 아브뉴프랑 지하 2층 (주)커피빈코리아 광명아브뉴프랑점',
 '서울특별시 종로구 새문안로 91 고려빌딩 1,2층',
 '서울특별시 송파구 법원로6길 11 환인빌딩 1층',
 '서울특별시 동대문구 경희대로 10 (회기동)',
 '경기도 파주시 문발로 131',
 '경상남도 창원시 성산구 원이대로 320, 더시티세븐S-105호(대원동)',
 '서울특별시 종로구 종로3길 34',
 '서울특별시 마포구 와우산로10길 3, 엘케이빌딩 1~3층',
 '경기도 안양시 동안구 시민대로 260, 1층 104,105호',
 '경기도 하남시 미사대로 750, 신세계백화점 지하1층 식품관',
 '서울특별시 종로구 우정국로 26 센트로폴리스 1층 Retail 1-5,6',
 '서울특별시 송파구 올림픽로35길 123 1층',
 '부산 부산진구 서면로 62-1 에이스메디컬타워 1F',
 '인천시 중구 신도시남로 142번길 6 (메가스타 영종 139,140,141호)',
 '서울특별시 중구 장충동2가 188-11, 188-4, 188-5',
 '부산 해운대구 센텀3로 20 해운대센텀호텔 1F 101호',
 '서울특별시 서초구 서초중앙로 156, 1층',
 '경기도 부천시 부천로25',
 '부산 중구 해관로 1 희남빌딩 1층',
 '광주광역시 서구 상무중앙로 9, 동양빌딩 1F',
 '경기도 김포시 태장로 819',
 '서울특별시 서초구 반포대로70',
 '경기도 남양주시 경춘로 1641',
 '서울특별시 강남구 봉은사로 331 SH빌딩점 B1-1층',
 '서울특별시 강서구 강서로 162',
 '경기도 부천시 옥길동 768 부천스타필드시티점 4층',
 '인천시 연수구 컨벤시아대로 60, 1층',
 '광주광역시 동구 서남동 서석로 44 1층 ~ 2층',
 '대구광역시 중구 동성로3길 106',
 '서울특별시 강남구 대치동 943-2 루첸타워 1층 로비',
 '경기도 수원시 팔달구 덕영대로 924 AK플라자 4층',
 '서울특별시 중구 을지로 35 하나은행 을지로본점 24F 내 스마트워크센터',
 '서울특별시 강남구 테헤란로69길 5 DT센터점 1층',
 '서울특별시 서초구 강남대로 563 페이토플라자 1층 ( 잠원동 37-1 )',
 '서울특별시 용산구 장문로 23 몬드리안 서울 이태원호텔 101호',
 '광주광역시 남구 봉선로 168',
 '서울특별시 노원구 동일로 1405, 1층 일부',
 '서울특별시 강남구 광평로 51길 6-23 원방테크사옥 1층',
 '서울특별시 송파구 송파대로 345 ( 헬리오시티상가 3블럭 A동 B1층 22호 )',
 '서울특별시 중구 남대문로10길 33 1F',
 '서울특별시 서초구 서초중앙로 209, 해성빌딩 1층',
 '경기도 고양시 일산동구 정발산로 38',
 '부산광역시 북구 학사로 8 (화명동 2312), 크리스탈타워 2층 201~202호',
 '경기도 용인시 처인구 역북동 598-7',
 '부산광역시 중구 중앙대로 102 팬오션빌딩 1F',
 '충청남도 천안시 동남구 만남로 48',
 '제주특별자치도 제주시 연북로 511',
 '서울특별시 종로구 대명길 5',
 '경기도 용인시 처인구 포곡읍 가실리 156-1 (파크내 홀랜드빌리지 옆 암스테르담)',
 '서울특별시 중구 명동 10길 52 명동역 신한은행 사옥 1층',
 '경기도 안양시 동안구 엘에스로 127 1층',
 '서울특별시 마포구 상암산로 82 SBS 프리즘 타워 1층 로비',
 '서울특별시 용산구 한강대로 23길 55, 아이파크몰 테이스트파크 7층',
 '경기도 이천시 대산로288번길 89, 행복1마을 복지A동 지하1층',
 '경상남도 진주시 충의로 19 LH진주사옥 공감동 1층',
 '서울특별시 중구 을지로 66 하나은행 명동사옥 1층',
 '제주특별자치도 제주시 애월읍 애월해안로 560',
 '서울특별시 종로구 성균관로 25-2 성균관대학교 법학관 B2',
 '경기도 화성시 동탄중앙로220 타임테라스A 블록 1층 110호-1호']

In [17]:
addr2 = pd.DataFrame(addr2, columns=['address2'])

addr2 #작업 내용 확인용 출력

                                  address2
0                     서울특별시 강남구 학동로 211 1층
1                서울특별시 강남구 논현로 566 강남차병원1층
2                    서울특별시 서초구 강남대로 369 1층
3                     서울특별시 서초구 서초 1306-3호
4      서울특별시 강남구 압구정로 461 네이처포엠빌딩B108,109호
..                                     ...
241          경상남도 진주시 충의로 19 LH진주사옥 공감동 1층
242           서울특별시 중구 을지로 66 하나은행 명동사옥 1층
243              제주특별자치도 제주시 애월읍 애월해안로 560
244      서울특별시 종로구 성균관로 25-2 성균관대학교 법학관 B2
245  경기도 화성시 동탄중앙로220 타임테라스A 블록 1층 110호-1호

[246 rows x 1 columns]

In [18]:
CB2 = pd.concat([CB, addr2], axis = 1)
CB2.head()

,store,address,phone,address2
0,학동역 DT점,서울시 강남구 학동로 211 1층,02-3444-9973,서울특별시 강남구 학동로 211 1층
1,차병원점,서울시 강남구 논현로 566 강남차병원1층,02-538-7615,서울특별시 강남구 논현로 566 강남차병원1층
2,강남대로점,서울시 서초구 강남대로 369 1층,02-588-5778,서울특별시 서초구 강남대로 369 1층
3,강남에스점,서울시 서초구 서초 1306-3호,02-593-5095,서울특별시 서초구 서초 1306-3호
4,청담에스점,"서울시 강남구 압구정로 461 네이처포엠빌딩B108,109호",02-548-6052,"서울특별시 강남구 압구정로 461 네이처포엠빌딩B108,109호"

In [19]:
CB2.to_csv('CoffeeBean_2.csv', encoding='CP949', index = False)

In [20]:
import folium

In [24]:
map_osm = folium.Map(location=[37.5599191, 126.9753407], zoom_start=15)

In [25]:
map_osm.save('map.html')

In [27]:
CB_file = pd.read_csv('CoffeeBean_2.csv', encoding='cp949')
CB_file.head()

,store,address,phone,address2
0,학동역 DT점,서울시 강남구 학동로 211 1층,02-3444-9973,서울특별시 강남구 학동로 211 1층
1,차병원점,서울시 강남구 논현로 566 강남차병원1층,02-538-7615,서울특별시 강남구 논현로 566 강남차병원1층
2,강남대로점,서울시 서초구 강남대로 369 1층,02-588-5778,서울특별시 서초구 강남대로 369 1층
3,강남에스점,서울시 서초구 서초 1306-3호,02-593-5095,서울특별시 서초구 서초 1306-3호
4,청담에스점,"서울시 강남구 압구정로 461 네이처포엠빌딩B108,109호",02-548-6052,"서울특별시 강남구 압구정로 461 네이처포엠빌딩B108,109호"

In [33]:
CB_geoData = pd.read_csv('CoffeeBean_2.add.csv', encoding='cp949', engine='python')
len(CB_geoData)

246

In [34]:
map_CB = folium.Map(location = [37.5599191, 126.9753407], zoom_start=15)

In [36]:
for i, store in CB_geoData.iterrows():
    folium.Marker(location=[store['Y'], store['X']], popup=store['store'],
                 icon=folium.Icon(color='red', icon='star')).add_to(map_CB)

In [37]:
map_CB.save('map_CB.html')

In [38]:
import webbrowser
webbrowser.open('map_CB.html')

True

In [39]:
import pandas as pd

In [41]:
# 승하차 인원 CSV 파일 읽어오기
data = pd.read_csv("seoul-metro-2020.logs.csv")

In [42]:
data

                             timestamp  station_code  people_in  people_out
0        2020-01-01T05:00:00.000+09:00           150        356         235
1        2020-01-01T06:00:00.000+09:00           150        280         952
2        2020-01-01T07:00:00.000+09:00           150        313         828
3        2020-01-01T08:00:00.000+09:00           150        774        1043
4        2020-01-01T09:00:00.000+09:00           150        923        1694
...                                ...           ...        ...         ...
2022795  2020-12-31T20:00:00.000+09:00          2827         86          71
2022796  2020-12-31T21:00:00.000+09:00          2827        112          99
2022797  2020-12-31T22:00:00.000+09:00          2827         45          39
2022798  2020-12-31T23:00:00.000+09:00          2827          6          25
2022799  2021-01-01T00:00:00.000+09:00          2827          0           3

[2022800 rows x 4 columns]

In [43]:
station_info = pd.read_csv("seoul-metro-station-info.csv")

station_info

,station.code,station.fr_code,line.num,line.name,line.name_sub,line.station_seq,station.name_full,station.name,station.name_chc,station.name_chn,station.name_en,station.name_jp,geo.latitude,geo.longitude,geo.sigungu_code,geo.sigungu_name,geo.addres_road,geo.address_land,geo.phone
0,158,124,1,1호선,지하철1호선,1,청량리(서울시립대입구),청량리|서울시립대입구,祭基洞,祭基洞,Jegidong,チェギドン,37.580178,127.046835,11060,동대문구,서울특별시 동대문구 왕산로 지하205(전농동),서울특별시 동대문구 전농동 620-69 청량리역(1호선),02-6110-1241
1,157,125,1,1호선,지하철1호선,2,제기동,제기동,新設洞,新设洞,Sinseoldong,シンソルトン,37.578103,127.034893,11060,동대문구,서울특별시 동대문구 왕산로 지하93(제기동),서울특별시 동대문구 제기동 65 제기동역(1호선),02-6110-1251
2,156,126,1,1호선,지하철1호선,3,신설동,신설동,東廟앞,东庙,Dongmyo,トンミョアプ,37.575297,127.025087,11060,동대문구,서울특별시 동대문구 왕산로 지하1(신설동),서울특별시 동대문구 신설동 76-5 신설동역(1호선),02-6110-1261
3,159,127,1,1호선,지하철1호선,4,동묘앞,동묘앞,淸凉里(서울市立大入口),清凉里(首尔市立大学),Cheongnyangni(University of Seoul),チョンニャンニ,37.572627,127.016429,11010,종로구,서울특별시 종로구 종로 359(숭인동),서울특별시 종로구 숭인동 117 동묘앞역(1호선),02-6110-1271
4,155,128,1,1호선,지하철1호선,5,동대문,동대문,東大門,东大门,Dongdaemun,トンデムン,37.571420,127.009745,11010,종로구,서울특별시 종로구 종로 지하302(창신동),서울특별시 종로구 창신동 492-1 동대문역(1호선),02-6110-1281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,2823,823,8,8호선,지하철8호선,14,남한산성입구(성남법원.검찰청),남한산성입구|성남법원|검찰청,南漢山城入口(城南法院檢察廳),南汉山城(城南法院·检察厅),Namhansanseong(Seongnam Court & Prosecutors' O...,ナムハンサンソンイック,37.451535,127.159816,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하445(단대동),경기도 성남시 수정구 단대동 96 남한산성입구역(8호선),02-6311-8231
281,2824,824,8,8호선,지하철8호선,15,단대오거리,단대오거리,丹垈오거리,丹垈五岔路口,Dandaeogeori,タンデオゴリ,37.445210,127.156866,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하365(신흥동),경기도 성남시 수정구 신흥동 2467 단대오거리역(8호선),02-6311-8241
282,2825,825,8,8호선,지하철8호선,16,신흥,신흥,新興,新兴,Sinheung,シンフン,37.440918,127.147564,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하280(신흥동),경기도 성남시 수정구 신흥동 2467 신흥역(8호선),02-6311-8251
283,2826,826,8,8호선,지하철8호선,17,수진,수진,壽進,寿进,Sujin,スジン,37.437428,127.140722,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하200(수진동),경기도 성남시 수정구 수진동 2205-1 수진역(8호선),02-6311-8261
284,2827,827,8,8호선,지하철8호선,18,모란,모란,牡丹,牡丹,Moran,モラン,37.432130,127.129087,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하100(수진동),경기도 성남시 수정구 수진동 4518 모란역(8호선),02-6311-8271

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2022800 entries, 0 to 2022799
Data columns (total 4 columns):
 #   Column        Dtype
---  ------        -----
 0   timestamp     object
 1   station_code  int64
 2   people_in     int64
 3   people_out    int64
dtypes: int64(3), object(1)
memory usage: 61.7+ MB

In [46]:
station_sum = data.groupby("station_code").sum()

station_sum

,timestamp,people_in,people_out
station_code,,,
150,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,12953773,12300397
151,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,6089772,6136935
152,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,10620727,10336642
153,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,8122680,7618514
154,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,6713475,6737470
...,...,...,...
2823,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,4039675,3655715
2824,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,3064607,2909492
2825,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,1400625,1494727
2826,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,1569471,1433100
2827,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,1395971,1083559

In [48]:
station_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285 entries, 0 to 284
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   station.code       285 non-null    int64
 1   station.fr_code    285 non-null    object
 2   line.num           285 non-null    int64
 3   line.name          285 non-null    object
 4   line.name_sub      285 non-null    object
 5   line.station_seq   285 non-null    int64
 6   station.name_full  285 non-null    object
 7   station.name       285 non-null    object
 8   station.name_chc   285 non-null    object
 9   station.name_chn   285 non-null    object
 10  station.name_en    285 non-null    object
 11  station.name_jp    285 non-null    object
 12  geo.latitude       285 non-null    float64
 13  geo.longitude      285 non-null    float64
 14  geo.sigungu_code   285 non-null    int64
 15  geo.sigungu_name   285 non-null    object
 16  geo.addres_road    285 non-null    object
 17  geo.address_land   285 non-null    object
 18  geo.phone          285 non-null    object
dtypes: float64(2), int64(4), object(13)
memory usage: 42.4+ KB

In [49]:
station_info = station_info.set_index('station.code')

station_info

,station.fr_code,line.num,line.name,line.name_sub,line.station_seq,station.name_full,station.name,station.name_chc,station.name_chn,station.name_en,station.name_jp,geo.latitude,geo.longitude,geo.sigungu_code,geo.sigungu_name,geo.addres_road,geo.address_land,geo.phone
station.code,,,,,,,,,,,,,,,,,,
158,124,1,1호선,지하철1호선,1,청량리(서울시립대입구),청량리|서울시립대입구,祭基洞,祭基洞,Jegidong,チェギドン,37.580178,127.046835,11060,동대문구,서울특별시 동대문구 왕산로 지하205(전농동),서울특별시 동대문구 전농동 620-69 청량리역(1호선),02-6110-1241
157,125,1,1호선,지하철1호선,2,제기동,제기동,新設洞,新设洞,Sinseoldong,シンソルトン,37.578103,127.034893,11060,동대문구,서울특별시 동대문구 왕산로 지하93(제기동),서울특별시 동대문구 제기동 65 제기동역(1호선),02-6110-1251
156,126,1,1호선,지하철1호선,3,신설동,신설동,東廟앞,东庙,Dongmyo,トンミョアプ,37.575297,127.025087,11060,동대문구,서울특별시 동대문구 왕산로 지하1(신설동),서울특별시 동대문구 신설동 76-5 신설동역(1호선),02-6110-1261
159,127,1,1호선,지하철1호선,4,동묘앞,동묘앞,淸凉里(서울市立大入口),清凉里(首尔市立大学),Cheongnyangni(University of Seoul),チョンニャンニ,37.572627,127.016429,11010,종로구,서울특별시 종로구 종로 359(숭인동),서울특별시 종로구 숭인동 117 동묘앞역(1호선),02-6110-1271
155,128,1,1호선,지하철1호선,5,동대문,동대문,東大門,东大门,Dongdaemun,トンデムン,37.571420,127.009745,11010,종로구,서울특별시 종로구 종로 지하302(창신동),서울특별시 종로구 창신동 492-1 동대문역(1호선),02-6110-1281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2823,823,8,8호선,지하철8호선,14,남한산성입구(성남법원.검찰청),남한산성입구|성남법원|검찰청,南漢山城入口(城南法院檢察廳),南汉山城(城南法院·检察厅),Namhansanseong(Seongnam Court & Prosecutors' O...,ナムハンサンソンイック,37.451535,127.159816,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하445(단대동),경기도 성남시 수정구 단대동 96 남한산성입구역(8호선),02-6311-8231
2824,824,8,8호선,지하철8호선,15,단대오거리,단대오거리,丹垈오거리,丹垈五岔路口,Dandaeogeori,タンデオゴリ,37.445210,127.156866,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하365(신흥동),경기도 성남시 수정구 신흥동 2467 단대오거리역(8호선),02-6311-8241
2825,825,8,8호선,지하철8호선,16,신흥,신흥,新興,新兴,Sinheung,シンフン,37.440918,127.147564,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하280(신흥동),경기도 성남시 수정구 신흥동 2467 신흥역(8호선),02-6311-8251
2826,826,8,8호선,지하철8호선,17,수진,수진,壽進,寿进,Sujin,スジン,37.437428,127.140722,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하200(수진동),경기도 성남시 수정구 수진동 2205-1 수진역(8호선),02-6311-8261
2827,827,8,8호선,지하철8호선,18,모란,모란,牡丹,牡丹,Moran,モラン,37.432130,127.129087,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하100(수진동),경기도 성남시 수정구 수진동 4518 모란역(8호선),02-6311-8271

KeyError: "None of ['station.code'] are in the columns"

In [53]:
joined_data = station_sum.join(station_info)

joined_data = joined_data.dropna()

joined_data

,timestamp,people_in,people_out,station.fr_code,line.num,line.name,line.name_sub,line.station_seq,station.name_full,station.name,...,station.name_chn,station.name_en,station.name_jp,geo.latitude,geo.longitude,geo.sigungu_code,geo.sigungu_name,geo.addres_road,geo.address_land,geo.phone
station_code,,,,,,,,,,,,,,,,,,,,,
150,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,12953773,12300397,133,1,1호선,지하철1호선,10,서울역,서울역,...,首尔站,Seoul Station,ソウルヨク,37.554648,126.972559,11020,중구,서울특별시 중구 세종대로 지하2(남대문로 5가),서울특별시 중구 남대문로5가 73-6 서울역(1호선),02-6110-1331
151,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,6089772,6136935,132,1,1호선,지하철1호선,9,시청,시청,...,市厅,City Hall,シチョン,37.564718,126.977108,11020,중구,서울특별시 중구 세종대로 지하101(정동),서울특별시 중구 정동 5-5 시청역(1호선),02-6110-1321
152,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,10620727,10336642,131,1,1호선,지하철1호선,8,종각,종각,...,钟阁,Jonggak,チョンガク,37.570161,126.982923,11010,종로구,서울특별시 종로구 종로 지하55(종로1가),서울특별시 종로구 종로1가 54 종각역(1호선),02-6110-1311
153,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,8122680,7618514,130,1,1호선,지하철1호선,7,종로3가(탑골공원),종로3가|탑골공원,...,钟路三街(塔谷公园),Jongno 3(sam)ga,チョンノサムガ,37.571607,126.991806,11010,종로구,서울특별시 종로구 종로 지하129(종로3가),서울특별시 종로구 종로3가 10-5 종로3가역(1호선),02-6110-1301
154,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,6713475,6737470,129,1,1호선,지하철1호선,6,종로5가,종로5가,...,钟路五街,Jongno 5(o)ga,チョンノオガ,37.570926,127.001849,11010,종로구,서울특별시 종로구 종로 지하216(종로5가),서울특별시 종로구 종로5가 82-1 종로5가역(1호선),02-6110-1291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2823,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,4039675,3655715,823,8,8호선,지하철8호선,14,남한산성입구(성남법원.검찰청),남한산성입구|성남법원|검찰청,...,南汉山城(城南法院·检察厅),Namhansanseong(Seongnam Court & Prosecutors' O...,ナムハンサンソンイック,37.451535,127.159816,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하445(단대동),경기도 성남시 수정구 단대동 96 남한산성입구역(8호선),02-6311-8231
2824,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,3064607,2909492,824,8,8호선,지하철8호선,15,단대오거리,단대오거리,...,丹垈五岔路口,Dandaeogeori,タンデオゴリ,37.445210,127.156866,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하365(신흥동),경기도 성남시 수정구 신흥동 2467 단대오거리역(8호선),02-6311-8241
2825,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,1400625,1494727,825,8,8호선,지하철8호선,16,신흥,신흥,...,新兴,Sinheung,シンフン,37.440918,127.147564,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하280(신흥동),경기도 성남시 수정구 신흥동 2467 신흥역(8호선),02-6311-8251
2826,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,1569471,1433100,826,8,8호선,지하철8호선,17,수진,수진,...,寿进,Sujin,スジン,37.437428,127.140722,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하200(수진동),경기도 성남시 수정구 수진동 2205-1 수진역(8호선),02-6311-8261
2827,2020-01-01T05:00:00.000+09:002020-01-01T06:00:...,1395971,1083559,827,8,8호선,지하철8호선,18,모란,모란,...,牡丹,Moran,モラン,37.432130,127.129087,31021,성남시수정구,경기도 성남시 수정구 산성대로 지하100(수진동),경기도 성남시 수정구 수진동 4518 모란역(8호선),02-6311-8271

In [55]:
seoul_in = folium.Map(location = [37.55, 126.98], zoom_start = 12)

seoul_in

In [57]:
from folium.plugins import HeatMap

HeatMap(data = joined_data[['geo.latitude', 'geo.longitude', 'people_in']]).add_to(seoul_in)

seoul_in

In [58]:
seoul_out = folium.Map(location=[37.55, 126.98], zoom_start = 12)

HeatMap(data = joined_data[['geo.latitude', 'geo.longitude', 'people_out']]).add_to(seoul_out)

seoul_out

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2022800 entries, 0 to 2022799
Data columns (total 4 columns):
 #   Column        Dtype
---  ------        -----
 0   timestamp     object
 1   station_code  int64
 2   people_in     int64
 3   people_out    int64
dtypes: int64(3), object(1)
memory usage: 61.7+ MB

In [60]:
morning_data = data[pd.to_datetime(data.timestamp).dt.hour < 9]
morning_data

                             timestamp  station_code  people_in  people_out
0        2020-01-01T05:00:00.000+09:00           150        356         235
1        2020-01-01T06:00:00.000+09:00           150        280         952
2        2020-01-01T07:00:00.000+09:00           150        313         828
3        2020-01-01T08:00:00.000+09:00           150        774        1043
19       2020-01-02T00:00:00.000+09:00           150         25          77
...                                ...           ...        ...         ...
2022780  2020-12-31T05:00:00.000+09:00          2827         49          15
2022781  2020-12-31T06:00:00.000+09:00          2827         88          59
2022782  2020-12-31T07:00:00.000+09:00          2827        246         111
2022783  2020-12-31T08:00:00.000+09:00          2827        314         181
2022799  2021-01-01T00:00:00.000+09:00          2827          0           3

[505700 rows x 4 columns]

In [62]:
evening_data = data[pd.to_datetime(data.timestamp).dt.hour > 17]

evening_data

                             timestamp  station_code  people_in  people_out
13       2020-01-01T18:00:00.000+09:00           150       3002        1922
14       2020-01-01T19:00:00.000+09:00           150       2857        1696
15       2020-01-01T20:00:00.000+09:00           150       2311        1620
16       2020-01-01T21:00:00.000+09:00           150       2523        1181
17       2020-01-01T22:00:00.000+09:00           150       1830         768
...                                ...           ...        ...         ...
2022794  2020-12-31T19:00:00.000+09:00          2827        140         162
2022795  2020-12-31T20:00:00.000+09:00          2827         86          71
2022796  2020-12-31T21:00:00.000+09:00          2827        112          99
2022797  2020-12-31T22:00:00.000+09:00          2827         45          39
2022798  2020-12-31T23:00:00.000+09:00          2827          6          25

[606840 rows x 4 columns]

In [63]:
morning_station_sum = morning_data.groupby("station_code").sum()

In [64]:
evening_station_sum = evening_data.groupby("station_code").sum()

In [ ]:
morning_joined_data = mornong